# ci.yml file for GitHub Actions
# https://github.com/TypeStrong/typedoc/issues/1485
name: CI Docs

on:
  push:
    branches:
      - main

jobs:
  docgen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "18.x"

      - name: Install
        run: yarn install

      - name: Test to see if the project compiles
        run: yarn build

      - name: Create the docs directory locally in CI
        run: yarn docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
